### ISSUE TITLE
--with-xorg-driver option generate error in branch master

### ISSUE THREAD

**Issue by illaxaer** [metalefty/X11RDP-RH-Matic#11]
In master branch option --with-xorg-driver generate error something like "there isn't dir xorg/server".
There aren't any errors In branch develop now.

Btw, for what need this xorg-driver? How can I use it in rdp? Any improvemtnts against x11rdp?

**Comment by metalefty** [comment]
Merged develop into master. Now master and develop branch are identical.

Choose "Session manager" instead of "sesman-X11rdp" then xorg rdp driver will be used. But it is still under development and experimental. Xorg rdp driver is lacking for some features already implemented in x11rdp so far. But xorg rdp driver will replace x11rdp in future.

The main reason why xorg rdp driver was born is to shorten build time, to reduce disk space to install to reduce disk space to build.

At present, `--with-xorg-driver` option is for people who know what xorg rdp driver is.
